---

- name: Update performance.conf config
  template: src=performance.conf.j2 dest={{config_dir_path}}/performance.conf
  register: perfconf

- name: Update postgres config
  lineinfile: dest={{config_dir_path}}/{{postgres_config}} line='include \'performance.conf\''
  register: pgconf

- debug: msg={{ (ansible_memtotal_mb/1024.0)|round|int }}
- debug: msg="shared_buffers {{ (((ansible_memtotal_mb/1024.0)|round|int)*0.25)|int*1024 }}MB"
- debug: msg="work_mem  {{ ((((ansible_memtotal_mb/1024.0)|round|int)*0.25)/max_connections*1024)|round|int }}MB"
- debug: msg="maintenance_work_mem  {{ ((ansible_memtotal_mb/1024.0)|round|int)*64 }}MB"
- debug: msg="effective_cache_size {{ (((ansible_memtotal_mb/1024.0)|round|int)*0.75)|int*1024 }}MB"

- name: Restart postgresql
  service: name=postgresql state=restarted
  when: pgconf.changed or pgconf.changed
